setup:
  addons:
  - plan: heroku-postgresql
    as: DATABASE

build:
  docker:
    web: web/Dockerfile

 config:
    RAILS_ENV: development
    FOO: bar
release:
  command:
    - ./deployment-tasks.sh
  image: worker
run:
  db: 
  web: /usr/local/bin/gunicorn -w 2 -b :8000 project:app
  asset-streamer:
    command:
      - python ./instance/db_create.py
    image: web


services:
  web:
    restart: always
    build: ./web/Dockerfile
    expose:
      - "8000"
    volumes:
      - ./web/project/static
    depends_on:
      - postgres
