
[scraper]
con_key = "SaaBBlfY7we6JQqqkB2p9nw4Q"
con_secret = "gULfLx6eaib93T4CbnmJxu76E3GoeKY20pBrHuSifRE9kth9Oy"
token = "1121123728702701571-wMHNZEK4rNOoDiyFTsYq7gorQSASSS"
token_secret = "OI6HFjoDvKOPue7Z16pabaV8IkYI00Ilc6gxbkJPI1uay"
